### ISSUE TITLE
Encountered error on docker-compose up

### ISSUE THREAD

**Issue by tony-garcia** [gregmoser/docker-lucee-mysql#1]
Hi Greg,
Great project -- thanks for putting this together. When I followed the instructions, I got this error message in my console:

ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

I had to delete the first two lines of docker-compose.yml (so that 'web' and 'appdb' were at the root of the configuration) for the containers to come up. Then things looked fine.
I'm running docker 1.9.1 and docker-compose 1.5.2 on OS X El Capitan.

**Comment by gregmoser** [comment]
Ahhh yes, hugely important point.  This uses docker-compose v2 style yml
which was released as part of 1.6

Maybe we should add a V1 version of the file and update the readme.
However v2 has a lot of power so maybe we should just explicitly state 1.6
as a requirement in the readme.

Thoughts?

**Comment by tony-garcia** [comment]
Yeah, I think adding the requirement of docker-compose v 1.6 in the docs would be sufficient (and IMO preferable to maintaining 2 versions of the file).

**Comment by gregmoser** [comment]
I see a PR in your future ;)

On Wed, Feb 17, 2016 at 6:57 AM Tony Garcia notifications@github.com wrote:
Yeah, I think adding the requirement of docker-compose v 1.6 in the docs would
be sufficient (and IMO preferable to maintaining 2 versions of the file).

**Comment by gregmoser** [comment]
This has been resolved.  Thanks, Tony!
