### ISSUE TITLE
Error on docker-compose up

### ISSUE THREAD

**Issue by gpearson** [gregmoser/docker-lucee-mysql#3]
Step 1/10 : From lucee/lucee-tomcat:4.5.1
ERROR: Service 'web' failed to build: repository licee/lucee-tomcat not found: does not exist or no pull access

Trying this Docker stuff that was learned at MuraCon 2017.

**Comment by gregmoser** [comment]
I think that you logged this issue against the wrong repo.  This repo never reference lucee/lucee-tomcat

**Comment by gpearson** [comment]
I cloned this repository with SourceTree then I entered the directory and followed the next step which was docker-compose up as noted below :

E:\Docker Files\Docker-Lucee-MySQL>docker-compose up
Pulling appdb (mysql:latest)...
latest: Pulling from library/mysql
5040bd298390: Pull complete
55370df68315: Pull complete
fad5195d69cc: Pull complete
a1034a5fbbfc: Pull complete
17f3570b42ae: Pull complete
6bf4b16e5339: Pull complete
9700c9731729: Pull complete
f2fea9c5b632: Pull complete
2f8101f5336d: Pull complete
0dc8f8a1031a: Pull complete
a1b9627588c7: Pull complete
Digest: sha256:5e2ec5964847dd78c83410f228325a462a3bfd796b6133b2bdd590b71721fea6
Status: Downloaded newer image for mysql:latest
Building web
Step 1/10 : FROM lucee/lucee-tomcat:4.5.1
ERROR: Service 'web' failed to build: repository lucee/lucee-tomcat not found: does not exist or no pull access

E:\Docker Files\Docker-Lucee-MySQL>



Then I received the error message.

**Comment by gregmoser** [comment]
I just pushed a fix for this yesturday: https://github.com/gregmoser/docker-lucee-mysql/commit/83263ff52dd46a0a32e6155a164e0aa994715bc9
